FROM nginx:latest
COPY ./site-content/index.html /usr/share/nginx/html/index.html
COPY ./site-content/js/main.js /usr/share/nginx/html/js/main.js
COPY ./site-content/css/style.css /usr/share/nginx/html/css/style.css
